<?php

use Illuminate\Database\Seeder;

class ContaContabilValorSeeder extends Seeder
{
    public function run()
    {
        DB::table('conta_contabil_valores')->insert([
            [
                'conta_id' => '5',
                'valor' => -1129.00,
                'conta_pagar_id' => 1,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -1188.00,
                'conta_pagar_id' => 2,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -100.00,
                'conta_pagar_id' => 3,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -1188.00,
                'conta_pagar_id' => 4,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -40.00,
                'conta_pagar_id' => 5,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -89.30,
                'conta_pagar_id' => 6,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -48.00,
                'conta_pagar_id' => 7,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -4.00,
                'conta_pagar_id' => 8,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -138.27,
                'conta_pagar_id' => 9,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -108.34,
                'conta_pagar_id' => 10,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -78.52,
                'conta_pagar_id' => 11,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'valor' => -60.00,
                'conta_pagar_id' => 12,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -269.00,
                'conta_pagar_id' => 13,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -10.00,
                'conta_pagar_id' => 14,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -15.30,
                'conta_pagar_id' => 15,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -575.15,
                'conta_pagar_id' => 16,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -5.00,
                'conta_pagar_id' => 17,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -30.00,
                'conta_pagar_id' => 18,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -29.90,
                'conta_pagar_id' => 19,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -22.00,
                'conta_pagar_id' => 20,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -816.40,
                'conta_pagar_id' => 21,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -872.00,
                'conta_pagar_id' => 22,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -972.00,
                'conta_pagar_id' => 23,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '6',
                'valor' => -872.00,
                'conta_pagar_id' => 24,
                'conta_receber_id' => null,
                'data_pagamento' => date('Y-m-d H:i:s'),
                'created_at' => date('Y-m-d H:i:s'),
            ],

        ]);
    }
}