<?php

use Illuminate\Database\Seeder;

class ContasAPagarSeeder extends Seeder
{
    public function run()
    {
        DB::table('contas_a_pagar')->insert([
            [
                'conta_id' => '3',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '1129',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 1",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '3',
                'tipo_despesa_id' => '2',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '2',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '1188',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 2",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '3',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '100.00',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 3",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '4',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '1188.00',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 4",
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'conta_id' => '4',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '40.00',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 5",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '4',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '89.30',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 6",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '48.00',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 7",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'tipo_despesa_id' => '2',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '2',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '4.50',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 8",
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'conta_id' => '5',
                'tipo_despesa_id' => '1',
                'centro_de_custo_id' => '1',
                'sub_tipo_pagamento_id' => '1',
                'fornecedor_id' => '1',
                'data_vencimento' => date('Y-m-d H:i:s'),
                'data_pagamento' => date('Y-m-d H:i:s'),
                'valor' => '138.27',
                'desconto' => '1',
                'deducao' => '1',
                'juros' => '1',
                'acrescimos' => '1',
                'descricao' => "Pagamento 9",
                'created_at' => date('Y-m-d H:i:s'),
            ]
        ]);
    }
}